### ISSUE TITLE
install depencies problems

### ISSUE THREAD

**Issue by Chasen-Zhang** [jarlef/vite-plugin-preload#1]
![image](https://user-images.githubusercontent.com/15354455/164953804-48b6d715-0cbd-4045-b9d7-a9eded08a5db.png)

**Comment by Chasen-Zhang** [comment]
This canvas doesn't seem to load
![image](https://user-images.githubusercontent.com/15354455/164955233-0b0f0a78-8639-4e28-9e67-af9cd71bec86.png)

**Comment by Chasen-Zhang** [comment]
@jarlef why added the canvas? I don't think you used it

**Comment by jarlef** [comment]
Sorry for the late answer. No. Thats correct. I have removed the dependency now.
