### ISSUE TITLE
Prefetching vs preloading

### ISSUE THREAD

**Issue by FTWinston** [jarlef/vite-plugin-preload#9]
Would you be open to a PR adding an option to specify `prefetch` or `modulepreload` behaviour?

That (`prefetch`) would seem better suited to my use case, where I've used code splitting to keep my landing page as small as possible.

I want to prefetch the contents of my "next" page in a way that won't take precedence over any resources that the landing page will request.

My understanding of `modulepreload` (or `preload`) is that the browser will wait for such resources to be loaded before rendering the page.
On the other hand, `prefetch` will tell it to load my "next" page only when idle.

The practical difference between the two is minimal in my case, but `prefetch` is more semantically correct for what I want to achieve. I expect there would be a more noticeable improvement in performance on larger sites.

**Comment by FTWinston** [comment]
My implementation so far has been to add a `rel` option, and have it treat css resources the same as js ones when `rel` is `preload`.

12f90e44873a

Clearly that's all debatable, so I'm happy to discuss, defer, or plough ahead with a PR if that's your preference.

**Comment by whytspace** [comment]
any chance this gets merged?
I also have a use case, where `preloading` (= wait for download) is an overkill, but `prefetching` (= ask to download as it might be needed at some point) seems useful.

**Comment by Tiagoperes** [comment]
This would also be really helpful to me. I have a very large application and compiling every module beforehand is not a good idea, but just pre fetching it would be great.

For now, I'll probably use another plugin to find-and-replace the phrase `rel="modulepreload"`.

**Comment by jarlef** [comment]
Sounds like a great idea.

**Comment by jarlef** [comment]
Have published  a new version with support for prefetch
